# Generated by Django 3.2.8 on 2022-05-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reviewrating_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='profile',
        ),
    ]
