# Generated by Django 3.2.8 on 2022-06-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_user'),
        ('app', '0003_auto_20220618_1508'),
    ]

    operations = [
    ]
