# Generated by Django 3.2.9 on 2022-03-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(choices=[('CHOCOLATE FUDGE', 'CHOCOLATE FUDGE'), ('CHOCOLATE MINT', 'CHOCOLATE MINT'), ('CHOCOLATE CHIP', 'CHOCOLATE CHIP'), ('RED VELVET', 'RED VELVET'), ('BLUE VELVET', 'BLUE VELVET'), ('GREEN VELVET', 'GREEN VELVET'), ('VANILLA', 'VANILLA'), ('COFFEE', 'COFFEE'), ('COCONUT', 'COCONUT'), ('GINGER', 'GINGER'), ('ZEBRA', 'ZEBRA'), ('CINNAMON', 'CINNAMON'), ('SPICE', 'SPICE'), ('MARBLE', 'MARBLE'), ('PINA COLADA', 'PINA COLADA'), ('LEMON', 'LEMON'), ('LIME', 'LIME'), ('BANANA', 'BANANA'), ('ORANGE', 'ORANGE'), ('PASSION JUICE', 'PASSION JUICE'), ('BUBBLEGUM', 'BUBBLEGUM'), ('CARROT', 'CARROT'), ('MINT', 'MINT'), ('OREO', 'OREO'), ('CARAMEL', 'CARAMEL'), ('BLUEBERRY', 'BLUEBERRY'), ('STRAWBERRY', 'STRAWBERRY'), ('BUTTER', 'BUTTER'), ('FRUIT', 'FRUIT'), ('BLACK FOREST', 'BLACK FOREST'), ('WHITE FOREST', 'WHITE FOREST'), ('BLUEBERRY FOREST', 'BLUEBERRY FOREST'), ('PASSION FRUIT FOREST', 'PASSION FRUIT FOREST')], default='VANILLA', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='topping',
            field=models.CharField(choices=[('SKITTLES', 'SKITTLES'), ('GUMMIES', 'GUMMIES'), ('FRUITS', 'FRUITS'), ('NUTS', 'NUTS'), ('OREOS', 'OREOS'), ('CHERRIES', 'CHERRIES'), ('CAKE SAIL', 'CAKE SAIL'), ('CAKE TOPPERS', 'CAKE TOPPERS'), ('ASSORTED CHOCOLATES', 'ASSORTED CHOCOLATES')], default='GUMMIES', max_length=60),
        ),
    ]
