# Generated by Django 3.2.9 on 2022-03-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220328_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
