# Generated by Django 3.2.9 on 2022-04-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapayment',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='contact',
            new_name='phone',
        ),
    ]
